server:
  port: 2222
  shutdown: "graceful"
spring:
  lifecycle:
    timeout-per-shutdown-phase: "20s"
  mail:
    host: localhost
    password: admin
    username: admin
    port: 25
    properties:
      mail.smtp.auth: true
      starttls.enable: true